In [142]:
import numpy as np
from random import randint

In [188]:
#Making matrix
N=int(input())
x=[0]*N

for i in range(N):
    x[i]=None
values=np.zeros(N)
for i in range(N):
    values[i]=float(randint(1,5))
matrix=np.zeros((N,N))
for i in range(N):
    matrix[i,i]=float(randint(1,5))
    if i!=0:
        matrix[i,i-1]=float(randint(1,5))
    if i!=N-1:
        matrix[i,i+1]=float(randint(1,5))
print(matrix)
print(values)

matrix2=matrix.copy()#for checking

for i in range(1,N):
    if matrix[i-1,i-1]!=0:
        k=matrix[i,i-1]/matrix[i-1,i-1]
        matrix[i]-=(matrix[i-1]*k)
        values[i]=values[i]-values[i-1]*k
    else:
        matrix[i],matrix[i-1]=matrix[i-1],matrix[i].copy()
        values[i],values[i-1]=values[i-1],values[i].copy()

for i in range(N):
    for j in range(N):
        matrix[i,j]=round(matrix[i,j],5)
flag=False

for i in range(N-1,-1,-1):
    for j in range(N-1,-1,-1):
        if matrix[i,j]!=0.:
            if x[j]==None:
                x[j]=values[i]/matrix[i,j]
            else:
                values[i]-=matrix[i,j]*x[j]
    if all(a==0 for a in matrix[i]) and values(i)!=0:
        flag=True
if flag==True:
    print('Matrix has no decision')
else:
    for i in range(N):
        print('x_', i+1,' = ', round(float(x[i]),2), sep='')

20
[[3. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [2. 5. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 2. 2. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 2. 5. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 3. 2. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 3. 2. 5. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 4. 1. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 2. 3. 3. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 4. 4. 4. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 3. 1. 2. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 4. 2. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 2. 4. 2. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 5. 1. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 1. 1. 4. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 3. 2. 4. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 5. 2. 5.

Проверим решение, умножив матрицу matrix2(копию исходной) на вектор x(полученное решение)

In [189]:
for i in range(N):
    s=0
    for j in range(N):
        s+=(x[j]*matrix2[i,j]) 
    print(s.round(), end=' ')
        

3.0 5.0 5.0 5.0 5.0 3.0 5.0 2.0 4.0 4.0 3.0 1.0 1.0 2.0 2.0 2.0 4.0 1.0 3.0 4.0 